spring.application.name=be

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.kzmqmfqldmrkzwfjqiep
spring.datasource.password=chutoanduc123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8082}

# Supabase Auth Configuration
supabase.jwt.secret=+8mtFrJ5uAHF+61WubO07ALzdBujMoTAKeWtEod02BWyrIocN+mekpMkgsp8+GR+CsCAjY5pLzIvo6iRDYdTyQ==

# JPA/Hibernate logging
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# VNPay Sandbox Configuration
vnpay.tmn-code=${VNPAY_TMN_CODE:Q97FK5M3}
vnpay.hash-secret=${VNPAY_HASH_SECRET:0T17CSBDBCOF5HU4BTYQD43ZOKTG56ST}
vnpay.pay-url=${VNPAY_PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
vnpay.return-url=${VNPAY_RETURN_URL:http://localhost:5173/payment/vnpay-callback}

